### ISSUE TITLE
Update Fig. 1.g

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-construction-usage-supporting-information#45]
## TODOs
- [x] take input from Chuan Xu
- [x] Make new screenshot of heart to make septum less thickened
- [x] 7 datasets for left cardiac atrium: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.3/atlas-as-cell-summaries.jsonld#L40266-L40301
- [x] 6 datasets for interventricular septum (disregard HuBMAP dataset, registered into wrong reference organ): https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.3/atlas-as-cell-summaries.jsonld#L11931-L11966 

## Code
https://github.com/cns-iu/hra-construction-usage-supporting-information/blob/main/hra_pop/figure_1_g_hra_pop.ipynb
